### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [hatred2k/hatredv3-cogs#4]
Fortnite no longer works on the most updated version of Red, giving the error code: 

    func.requires.privilege_level = privilege_level
AttributeError: 'Group' object has no attribute 'requires'

**Comment by hatred2k** [comment]
I just updated to account for the most recent change and it's working fine for me. Are you still getting that? If so, what command are you using and could you paste the entire traceback?

**Comment by rawxxi** [comment]
Not working for me.
